# Site settings
title: Postgresql Discovery
email: pkorobeinikov@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Блог о исследовании внутреннего устройства СУБД Postgresql.
baseurl: ""
url: "http://postgresql-discovery.ru"
twitter_username: pkorobeinikov
github_username:  pkorobeinikov

# Build settings
#markdown: kramdown
